### ISSUE TITLE
`mackup backup` asks to replace `.z` every time

### ISSUE THREAD

**Issue by mxcl** [lra/mackup#818] opened 2016-05-19 21:33 UTC
<img width="762" alt="screen shot 2016-05-19 at 2 26 55 pm" src="https://cloud.githubusercontent.com/assets/58962/15410299/d4b0a066-1dcd-11e6-83b6-3cbe46a5ac6c.png">

``` sh
$ mackup --version
Mackup 0.8.14

$ cd $(dirname $(which mackup)) && cd $(dirname $(readlink mackup))/.. && pwd
/usr/local/Cellar/mackup/0.8.14
```

**Comment by chew-z** [comment] 2016-08-31 13:24
Yes. I think at every command prompt z does overwrite '.z' file destroying symlink. 
It is bad idea to mackup z file and it should be excluded.

**Comment by lra** [comment] 2016-09-01 19:01
Mind making a PR? If not let me know and I'll do it.

**Comment by paxperscientiam** [comment] 2018-09-05 17:39
Just chiming in to say that this is still a bug.

**Comment by joshmedeski** [comment] 2018-09-10 16:53
If you don't want to back up your `.z` file you can add this to your `.mackup.cfg` file.

```
[applications_to_ignore]
z
```

😄

**Comment by lra** [comment] 2018-09-10 20:56
@joshmedeski is right for a workaround.

Regarding Z's support, looks like [I removed it](https://github.com/lra/mackup/pull/484#commitcomment-10830607) in the past and [merged a PR later](https://github.com/lra/mackup/pull/677) to add support again.

I'll remove it again... I'd really love contributors to test their additions as I can't test evert application out there 😩

**Closed** 2018-09-10 20:59 UTC

**Comment by paxperscientiam** [comment] 2018-09-11 04:30
Frustrating, I'm sure. Do you know what the underlying issue was with z?

**Comment by lra** [comment] 2018-09-11 21:45
If it's confirmed, yes. Can you test it?

**Comment by joshmedeski** [comment] 2018-09-11 21:54
haha yeah, I'll test it tonight. I ignored it just like my suggestion here on `z`. I'll even make a PR if I can confirm the same problem.

**Comment by lra** [comment] 2018-09-11 22:07
Awesome!
