### ISSUE TITLE
uninstall for specified application?

### ISSUE THREAD

**Issue by xingheng** [lra/mackup#1466] opened 2019-09-24 14:24 UTC
I just found something unwanted applications kept sync to dropbox storage, generally I tried to add it the ignored list in `.mackup.cfg` file and run `mackup uninstall` and `mackup backup`, however this make a big changes which I found in Dropbox sync status.

So, I'm thinking why not having a command to uninstall a specified application to original state and I'll add it the ignore list manually later. No `uninstall` and `backup` commands are needed.

Or am I misunderstand something? Please...

**Comment by Drallas** [comment] 2020-01-06 08:04
I'm also looking for an option like this. Did you find out if it's possible?

**Comment by xingheng** [comment] 2020-01-06 08:33
Not yet, still use the manual way.

**Comment by halloleo** [comment] 2020-01-22 05:35
That would be a great feature! Would be sooo much easier than manually "uninstalling" the links of apps you don't want to sync anymore.

**Comment by lra** [comment] 2020-02-27 02:49
Yes. Dupe of https://github.com/lra/mackup/issues/611

**Closed by lra** 2020-02-27 02:49 UTC
