### ISSUE TITLE
Command Line Option for `--all` and specific apps

### ISSUE THREAD

**Issue by joeyhoer** [lra/mackup#573] opened 2015-06-18 15:35 UTC
Occasionally I'll be working in an application on a machine, realize I want to backup or restore preferences, but I'm not sure of the state of the other applications on the system, and I don't want to blow away my current backup or my current configuration.

It would be nice if you could backup just a single application with:

    mackup backup app

Or backup multiple applications with:

    mackup backup app1 app2

And backup all applications with something like:

    mackup backup --all

Restoring/Uninstalling may follow the same process.

Making the process more verbose, and more secure, so simply typing `mackup backup/restore` won't replace file unintentionally.

**Comment by lra** [comment] 2015-08-09 23:12
Dupe of https://github.com/lra/mackup/issues/611

**Closed by lra** 2015-08-09 23:12 UTC
