### ISSUE TITLE
Problem if link already exists

### ISSUE THREAD

**Issue by Tam-Lin** [lra/mackup#83] opened 2013-06-25 21:55 UTC
I'll add as a comment for now, but if you're running ./mackup restore, and there's already a link there that points to nowhere, the restore process blows up.  

> Restoring Library/Preferences/org.pqrs.KeyRemap4MacBook.plist...
Restoring Library/Application Support/KeyRemap4MacBook/private.xml...
Traceback (most recent call last):
  File "./mackup.py", line 925, in <module>
    main()
  File "./mackup.py", line 886, in main
    app.restore()
  File "./mackup.py", line 459, in restore
    home_filepath))):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 154, in samefile
    s2 = os.stat(f2)
OSError: [Errno 2] No such file or directory: '/Volumes/Users/kdm/Library/Application Support/Adobe/Lightroom/Develop Presets'

In this case, /Volumes/Users/kdm/Library/Application Support/Adobe/Lightroom/Develop Presets was a link pointing to a directory that didn't exist any more.  Once I rmed the link, the restore completed successfully.

**Comment by lra** [comment] 2015-08-10 00:38
Dupe of https://github.com/lra/mackup/issues/612

**Closed by lra** 2015-08-10 00:38 UTC
