### ISSUE TITLE
Error on macOS Sonoma

### ISSUE THREAD

**Issue by cheginit** [lra/mackup#1950] opened 2023-10-23 03:03 UTC
I installed `mackup` on macOS Sonoma using `pip`. When I run the `mackup backup` command, I get the following error:

```
Backing up Library/Group Containers/com.apple.PreviewLegacySignaturesConversion/Library/Preferences ...
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/lib/python3.11/site-packages/mackup/application.py", line 115, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/opt/homebrew/lib/python3.11/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/user/Library/Group Containers/com.apple.PreviewLegacySignaturesConversion/Library/Preferences'
```

It appears that the folder `/Users/user/Library/Group Containers/com.apple.PreviewLegacySignaturesConversion` does not exist.

**Comment by GentleHoneyLover** [comment] 2023-10-26 15:43
Same here. Was setting up a new Mac and could't do  `mackup restore` :((

**Comment by frederikkempe** [comment] 2023-10-27 19:25
Having the same issue setting up a new Macbook. First thing that came to mind was that it was something related to which Python version was running on my machine. Tried different versions though and nothing seems to work.

**Comment by sethherr** [comment] 2023-10-30 18:03
Seems to be a duplicate of #1948

**Closed** 2023-11-05 21:42 UTC

**Comment by lra** [comment] 2023-11-05 21:44
> Seems to be a duplicate of #1948

No it's a problem with the Preview app. It will be removed in the next version, thanks.
