### ISSUE TITLE
Problem after uninstall

### ISSUE THREAD

**Issue by pedrovillalobos** [lra/mackup#97] opened 2013-07-24 22:06 UTC
After uninstalling the app, using sudo ./mackup uninstall, everytime I restart my machine I loose all the configuration from the previous backup up apps. I have to re-register and reconfigure all of them.

**Comment by lra** [comment] 2015-08-10 00:39
Dupe of https://github.com/lra/mackup/issues/612

**Closed by lra** 2015-08-10 00:39 UTC
