### ISSUE TITLE
Add location parameter to "mackup restore" command

### ISSUE THREAD

**Issue by JayDeuce** [lra/mackup#260] opened 2014-05-21 00:45 UTC
SITUATION: I use the File_System Storage option in my .mackup.cfg file to store to my backups to my Dropbox/Apps/Mackup folder. When using mackup restore it will only look in the default Dropbox/Mackup location. I can fix it by first copying the .mackup.cfg file to my user home folder and then run the command, but then what is the point of using mackup to backup itself.

FIX: Give the ability to pass a location parameter for the mackup restore command for it to look for the backups. example: "mackup restore ~/dropbox/apps/mackup"

**Comment by lra** [comment] 2015-08-10 03:00
Dupe of https://github.com/lra/mackup/issues/294

**Closed by lra** 2015-08-10 03:00 UTC
