### ISSUE TITLE
Backup of p10k zsh config file

### ISSUE THREAD

**Issue by adima959** [lra/mackup#1640] opened 2020-09-30 07:05 UTC
Hey All, 

Trying to backup p10k file which his located at 

Error when I run mackup backup
```
❯ mackup backup
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.29', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.29/libexec/lib/python3.8/site-packages/mackup/main.py", line 91, in main
    app = ApplicationProfile(mckp, app_db.get_files(app_name), dry_run, verbose)
  File "/usr/local/Cellar/mackup/0.8.29/libexec/lib/python3.8/site-packages/mackup/appsdb.py", line 141, in get_files
    return self.apps[name]["configuration_files"]
KeyError: 'p10k-custom'
```

My .mackup/p10k.cfg file
```
[application]
name = p10k-custom

[configuration_files]
#/User/xxxx/p10k.zsh
#.p10k.zsh
#~/.p10k.zsh
```
The commented files above are just to illustrate all paths I tried individually, but none of them work. 

Any help would be appreciated.

**Comment by rlam3** [comment] 2020-10-14 13:59
@adima959 were you able to find a workaround?

**Comment by adima959** [comment] 2020-10-15 06:42
Unfortunately I didn't find any solution. Wish someone could help. :) 

Are you having the same issue?

**Comment by rlam3** [comment] 2020-10-23 00:03
@adima959 I think its best to reinstall mackup and try again.
```
brew install mackup --HEAD
```

**Comment by OrangeFran** [comment] 2020-11-21 08:07
@adima959 
I don't know if this is the intended behavior but try to use the name "p10k" instead of the "p10k-custom" one. in your `~/.mackup.cfg` file.
I just tried it out and it seems like mackup uses the name of the `.cfg` file and not the one specified in the `[application]` paragraph.

**Comment by lra** [comment] 2021-01-04 13:07
You are right, this has been explained in https://github.com/lra/mackup/commit/e82a260934dc1d4c879ce2bc326de86d16cbea74#diff-a0842ea73f3a116eff7958fbf833dd2280c366c0d8985aa05f8e1403e0f39273
Closing this as fixed.

**Closed by lra** 2021-01-04 13:07 UTC
