### ISSUE TITLE
Crash while backing up Atom

### ISSUE THREAD

**Issue by Anahkiasen** [lra/mackup#246] opened 2014-04-02 13:31 UTC
Got this when trying to backup my `.atom` folder :

```
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 26, in <module>
    mackup.main.main()
  File "/usr/local/Cellar/mackup/0.7.2/lib/python2.7/site-packages/mackup/main.py", line 48, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.7.2/lib/python2.7/site-packages/mackup/application.py", line 83, in backup
    utils.copy(filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.7.2/lib/python2.7/site-packages/mackup/utils.py", line 91, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/anahkiasen/.atom/packages/emmet/node_modules/.bin/csonc', '/Users/anahkiasen/Dropbox/Mackup/.atom/packages/emmet/node_modules/.bin/csonc', "[Errno 2] No such file or directory: '/Users/anahkiasen/.atom/packages/emmet/node_modules/.bin/csonc'"), ('/Users/anahkiasen/.atom/packages/emmet/node_modules/season/node_modules/.bin/cake', '/Users/anahkiasen/Dropbox/Mackup/.atom/packages/emmet/node_modules/season/node_modules/.bin/cake', "[Errno 2] No such file or directory: '/Users/anahkiasen/.atom/packages/emmet/node_modules/season/node_modules/.bin/cake'"), ('/Users/anahkiasen/.atom/packages/emmet/node_modules/season/node_modules/.bin/coffee', '/Users/anahkiasen/Dropbox/Mackup/.atom/packages/emmet/node_modules/season/node_modules/.bin/coffee', "[Errno 2] No such file or directory: '/Users/anahkiasen/.atom/packages/emmet/node_modules/season/node_modules/.bin/coffee'"), ('/Users/anahkiasen/.atom/packages/emmet/node_modules/season/node_modules/fs-plus/node_modules/.bin/rimraf', '/Users/anahkiasen/Dropbox/Mackup/.atom/packages/emmet/node_modules/season/node_modules/fs-plus/node_modules/.bin/rimraf', "[Errno 2] No such file or directory: '/Users/anahkiasen/.atom/packages/emmet/node_modules/season/node_modules/fs-plus/node_modules/.bin/rimraf'"), ('/Users/anahkiasen/.atom/packages/travis-ci-status/node_modules/.bin/travis-ci', '/Users/anahkiasen/Dropbox/Mackup/.atom/packages/travis-ci-status/node_modules/.bin/travis-ci', "[Errno 2] No such file or directory: '/Users/anahkiasen/.atom/packages/travis-ci-status/node_modules/.bin/travis-ci'")]
```

**Comment by ArnaudRinquin** [comment] 2015-01-26 10:20
Something similar here:
```
Mackup needs a directory to store your configuration files
Do you want to create it now ? </Users/arnaudrinquin/Dropbox/Mackup> <Yes|No>yes
Backing up /Users/arnaudrinquin/.atom/packages ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.1/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.1', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.1/libexec/lib/python2.7/site-packages/mackup/main.py", line 49, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.1/libexec/lib/python2.7/site-packages/mackup/application.py", line 89, in backup
    utils.copy(filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.1/libexec/lib/python2.7/site-packages/mackup/utils.py", line 97, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/arnaudrinquin/.atom/packages/my-package', '/Users/arnaudrinquin/Dropbox/Mackup/.atom/packages/my-package', "[Errno 2] No such file or directory: '/Users/arnaudrinquin/.atom/packages/my-package'")]
```

**Comment by damiankloip** [comment] 2015-01-30 11:10
So I think syncing packages is still a problem, and still the case in the current MASTER. Let's remove that?

**Comment by lra** [comment] 2015-01-30 19:22
Merged your PR in master, let's see if it solves the problem.

**Comment by techniq** [comment] 2015-06-16 18:43
After this change it is no longer possible to restore your installed packages.  Atom doesn't keep a list of installed packages, but you can [generate](https://discuss.atom.io/t/how-to-backup-all-your-settings/15674) one using `apm list --installed --bare > packages.list` and then restore them using ```apm install `cat packages.list` ```

There is also a package to manage packages - `https://github.com/Hackafe/atom-sync-settings` which I'm using now until Mackup handles packages correctly



It doesn't appear there is a way to restore your packages now after this change.  Atom doesn't keep a package.json

**Comment by lra** [comment] 2015-06-16 21:53
what should mackup sync?

**Comment by techniq** [comment] 2015-06-17 01:15
I don't know if mackup can, but it would be best if it could run `apm list --installed --bare > packages.list` on `mackup backup` and then run ```apm install `cat packages.list` ```.  The problem is (as far as I know) Atom doesn't persist to disk the list of packages beyond the actual installed directories, which causes all the problems (and are really heavy to backup all those assets)

**Comment by damiankloip** [comment] 2015-06-17 07:33
I don't think that's really how mackup works. It doesn't run as a background process and `mackup backup` is just run to symlink all your conf files. Mackup could just add `.atom/packages.list` to it's mackup config but this is just a suggested way to do things from a comment thread. You could do pretty much the same with any package manager.

I would suggest just adding a custom mackup config to your `~/.mackup` directory like [this](https://gist.github.com/damiankloip/b4ea46db79c5f125861d).

**Comment by lra** [comment] 2015-06-17 15:21
should we remove atom support for mackup then?

**Comment by damiankloip** [comment] 2015-06-17 15:30
Personally, I think it's still useful. You still get all your regular config files synced.

@techniq is expecting mackup to do something it doesn't do IMO :) Like I said before, we could just add packages.list to the list of files to sync or something, but that is not anything concrete, it's a suggestion from a comment thread.

So a simple local override for the people using that method seems ok to me.. Especially with the gist I linked to above, you could just do `https://gist.githubusercontent.com/damiankloip/b4ea46db79c5f125861d/raw/c4013615bc5ed6da85ff36fc09dd6f16c4925f2e/atom-extra.cfg > ~/.mackup/atom-extra.cfg`

Another option is to just have an additional folder that is synced that files could live in?

**Comment by techniq** [comment] 2015-06-17 18:09
I don't think removing Atom support is needed, as there is still use in getting the config, keymaps, styles, etc.   I was just bring up the fact before #451, performing a `mackup backup`, delete `~/.atom` and then `mackup restore`, your editor would be stored before blowing away the directory.  Now, all your packages are lost (which is a big deal IMO).  

I think @damiankloip suggestion for custom custom config is the way to go (for now).  After doing `https://gist.githubusercontent.com/damiankloip/b4ea46db79c5f125861d/raw/c4013615bc5ed6da85ff36fc09dd6f16c4925f2e/atom-extra.cfg > ~/.mackup/atom-extra.cfg`, the following workflow *should* be possible.

- `apm list --installed --bare > packages.list && mackup backup`
- `mackup restore && apm install `cat packages.list`

**Comment by lra** [comment] 2015-08-10 03:05
Fixed in https://github.com/lra/mackup/commit/4b961f893f0f0b8c6563d1bceb317b5a15f11b96#diff-71aff7313d191778531bffb35ad2f1ab

**Closed by lra** 2015-08-10 03:05 UTC
