### ISSUE TITLE
Seperate app database from program source

### ISSUE THREAD

**Issue by josephholsten** [lra/mackup#1055] opened 2017-09-12 21:34 UTC
I can think of a few reasons to separate the files into two repos:
- reduces the lower barrier to entry for both sets of code
- allows the database to have more maintainers to burn down that PR backlog
- other tools would be able to build on the app database

Are there any strong reasons not to split?

**Comment by lra** [comment] 2017-09-13 04:56
Yeah, lots of good reasons, but we would need to build an engine able to pull this database on demand in mackup.

Not technically hard, just need to be done.

Duplicate of https://github.com/lra/mackup/issues/506

**Comment by lra** [comment] 2017-09-13 04:56
Duplicate of https://github.com/lra/mackup/issues/506

**Closed by lra** 2017-09-13 04:56 UTC
