### ISSUE TITLE
tunnelblick - config alias  

### ISSUE THREAD

**Issue by Ashtonian** [lra/mackup#1525] opened 2020-02-19 23:36 UTC
Is there another way mack up could backup Tunnelblick configs? I believe making the configs an alias breaks it. 

https://github.com/Tunnelblick/Tunnelblick/issues/607

**Comment by lra** [comment] 2020-02-27 02:11
Not sure why Tunnelblick is doing this, but for those, the only solution would be to copy the files instead of linking those, but this is not a simple problem.

Dupe of https://github.com/lra/mackup/issues/613

**Closed by lra** 2020-02-27 02:11 UTC
