### ISSUE TITLE
List only apps that exist on current host

### ISSUE THREAD

**Issue by haakonstorm** [lra/mackup#1331] opened 2019-03-05 05:57 UTC
## `Suggestion 1: "# mackup listlocal"`

**`# mackup listlocal`**

To list only apps **currently available on current host**. Something along these lines:
```
Usage:
 mackup list
 mackup listlocal
 mackup [options] backup
 mackup [options] restore
 mackup [options] uninstall
 mackup (-h | --help)
 mackup --version

Options:
 -h --help     Show this screen.
 -f --force    Force every question asked to be answered with "Yes".
 -n --dry-run  Show steps without executing.
 -v --verbose  Show additional details.
 --version     Show version.

Modes of action:
1. list: display a list of all supported applications.
2. listlocal: display a list of all supported applications found on this local host**
(...)
```
The idea is that:
**`# mackup listlocal >> .mackup.cfg `**
can prepopulate the config file so it is easier to sort apps into:
```
[applications_to_sync]
irssi
ventrilo
xemacs

[applications_to_ignore]
xcode
rstudio
```
Because today, when I ran the utility for the first time with --dry-run, I got a list like this:
**`# mackup --dry-run backup`**
```
Backing up .MacOSX ...
Backing up Library/KeyBindings/DefaultKeyBinding.dict ...
Backing up Library/ColorSync/Profiles ...
Backing up .hgignore_global ...
Backing up Library/Application Support/Many Tricks ...
Backing up .npmrc ...
Backing up Library/Preferences/com.kapeli.dashdoc.plist ...
Backing up Library/KeyBindings/DefaultKeyBinding.dict ...
Backing up Library/Services ...
Backing up Library/Workflows ...
Backing up .config/omf ...
Backing up .subversion ...
```
I am not sure which apps all items in this list belong to. If instead we could do something like:

**`# mackup listlocal`**
```
xcode
sublime-text-3
alfred3
rstudio
```
(notice the dashes ("-") are removed from this view, to be compatible with .mackup.cfg)
This way your could immediately edit the cfg to select which Apps I want to exclude.

## `Suggestion 2: "# mackup setup"`
Additionally, another way perhaps even _better_ would be something like:

**`10core.local: # mackup setup`**
```
Searching for locally installed apps supported by the sync engines ...
Searching for available sync backends ...
Defaulting to all apps INCLUDED for sync ...
Building ~/.mackup.cfg for this particular host 10core.local ...
Done
```
Resulting in a `.mackup.cfg` created and prepopulated with:
* Preconfigured, commented-out configuration suggestion for sync backends found (iCloud/git/Dropbox/~/..)
* Preconfigured includes/excludes, defaulting to either all apps included or all apps excluded, or user selectable? 
* Perhaps for each app, lines listing the files queued for sync so they can be user included/excluded on a per-file-per-app basis?

Just my 0.02 satoshis, 
thanks for a great utility! 
And for Pouet! 
<3 from Oslo

**Comment by zenozen** [comment] 2019-06-26 06:04
I really like this proposal. Otherwise `mackup list` is not very useful, having 400+ programs listed, most of which each individual user doesn't even recognize.

**Comment by lra** [comment] 2019-07-11 01:12
Dupe of https://github.com/lra/mackup/issues/603

**Closed by lra** 2019-07-11 01:12 UTC
