### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by churnd** [lra/mackup#500] opened 2015-04-01 19:02 UTC
I'm trying to sync OmniGraffle & the built-in support doesn't seem to work.  I tried adding my own:

>$ cat omnigraffle_new.cfg 
>[application]
>name = omnigraffle_new
>
>[configuration_files]
>Library/Containers/com.omnigroup.OmniGraffle6
>Library/Containers/com.omnigroup.GraffleLayout
>Library/Preferences/com.omnigroup.OmniGraffle6.LSSharedFileList.plist

Trying to run it gets me this:

>$ mackup backup
>Backing up /Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6 ...
>A folder named /Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6 already exists in the backup.
>Are you sure that you want to replace it ? <Yes|No>yes
>Traceback (most recent call last):
>  File "/usr/local/Cellar/mackup/0.8.5/libexec/bin/mackup", line 9, in <module>
>    load_entry_point('mackup==0.8.5', 'console_scripts', 'mackup')()
>  File "/usr/local/Cellar/mackup/0.8.5/libexec/lib/python2.7/site-packages/mackup/main.py", line 50, in main
>    app.backup()
>  File "/usr/local/Cellar/mackup/0.8.5/libexec/lib/python2.7/site-packages/mackup/application.py", line 85, in backup
>    utils.copy(filepath, mackup_filepath)
>  File "/usr/local/Cellar/mackup/0.8.5/libexec/lib/python2.7/site-packages/mackup/utils.py", line 98, in copy
>    shutil.copytree(src, dst)
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
>    raise Error, errors
>shutil.Error: [('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Documents/iChats', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Documents/iChats', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Documents/iChats'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Application Scripts/com.omnigroup.OmniGraffle6', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Application Scripts/com.omnigroup.OmniGraffle6', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Application Scripts/com.omnigroup.OmniGraffle6'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/ColorSync', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/ColorSync', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/ColorSync'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Components', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Components', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Components'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Images/People', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Images/People', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Images/People'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/KeyBindings', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/KeyBindings', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/KeyBindings'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/ByHost/com.omnigroup.OmniSoftwareUpdate.FD58C988-C041-5BDD-9E16-396188B9A0A9.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/ByHost/com.omnigroup.OmniSoftwareUpdate.FD58C988-C041-5BDD-9E16-396188B9A0A9.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/ByHost/com.omnigroup.OmniSoftwareUpdate.FD58C988-C041-5BDD-9E16-396188B9A0A9.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.avfoundation.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.avfoundation.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.avfoundation.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.cmio.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.cmio.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.cmio.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.coremedia.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.coremedia.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.coremedia.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.coremediaio.support.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.coremediaio.support.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.coremediaio.support.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.corevideo.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.corevideo.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.corevideo.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.inputmethodkit.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.inputmethodkit.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.inputmethodkit.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.LaunchServices.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.LaunchServices.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.LaunchServices.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.MultitouchSupport.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.MultitouchSupport.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.MultitouchSupport.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.opengl.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.opengl.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.opengl.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.security.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.security.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.security.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.security_common.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.security_common.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.security_common.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.speech.synthesis.general.prefs.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.speech.synthesis.general.prefs.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.speech.synthesis.general.prefs.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.speech.voice.prefs.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.speech.voice.prefs.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.speech.voice.prefs.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.systemsound.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.systemsound.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.apple.systemsound.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.nvidia.OpenGL.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.nvidia.OpenGL.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.nvidia.OpenGL.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.omnigroup.OmniSoftwareUpdate.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.omnigroup.OmniSoftwareUpdate.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/com.omnigroup.OmniSoftwareUpdate.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/pbs.plist', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/pbs.plist', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/Preferences/pbs.plist'"), ('/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/QuickLook', '/Users/churnd/Documents/Dropbox/.dotmac/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/QuickLook', "[Errno 2] No such file or directory: '/Users/churnd/Library/Containers/com.omnigroup.OmniGraffle6/Data/Library/QuickLook'")]

**Comment by vitorgalvao** [comment] 2015-04-01 19:21
[Know issue](https://github.com/lra/mackup/issues/154). Mackup can’t handle those, [because it relies on symlinking](https://github.com/lra/mackup/issues/195).

**Comment by lra** [comment] 2015-08-09 23:23
Dupe of https://github.com/lra/mackup/issues/613

**Closed by lra** 2015-08-09 23:23 UTC
