### ISSUE TITLE
"mackup list" improvements 

### ISSUE THREAD

**Issue by aristidesfl** [lra/mackup#560] opened 2015-06-02 21:02 UTC
`mackup list` would be more useful if it showed only the installed applications which are supported.
It would also be useful if there was an indicator next to each app name showing if it is currently backed up or not.

If showing the full list of supported applications is considered important, it could be presented with `mackup list all` or some variation of that.

**Comment by lra** [comment] 2015-06-02 22:33
See `mackup status` in the [TODO](https://github.com/lra/mackup/blob/master/TODO.md)

**Comment by lra** [comment] 2015-08-09 23:13
Dupe of https://github.com/lra/mackup/issues/603

**Closed by lra** 2015-08-09 23:13 UTC
