### ISSUE TITLE
Fantastical 2 removes Mackup symlink 

### ISSUE THREAD

**Issue by zharmany** [lra/mackup#974] opened 2017-02-11 08:23 UTC
I was trying to use Mackup to sync my Fantastical 2 (Mac App Store v. 2.3.3 (422.57.ecaafb0)) settings and noticed some odd behavior. Whenever I launch or quit Fantastical 2 on macOS Sierra (10.12.3), the symlink

`~/Library/Containers/com.flexbits.fantastical2.mac/Container.plist` 

pointing to 

`~/Dropbox/Mackup/Library/Containers/com.flexibits.fantastical2.mac/Container.plist` 

is overwritten by the non-symlink file `Container.plist`. This behavior is not present on OS X El Capitan (10.11.6). I'm using Mackup 0.8.16 installed via Homebrew.

Steps to reproduce on launch:
1. Make sure Fantastical 2 is not running
2. `mackup restore`
3. Check that symlink is present
4. Launch Fantastical 2
5. Notice symlink is removed

Steps to reproduce on exit:
1. Make sure Fantastical 2 is running
2. `mackup restore`
3. Check that symlink is present
4. Quit Fantastical 2
5. Notice symlink is removed

Anyone else experiencing similar behavior? Thanks for the awesome work on Mackup!!

Edit: This behavior also persists across system restarts - I was worried that, perhaps, macOS was restoring a cached version of the preferences.

**Comment by dodekeract** [comment] 2017-02-11 12:20
That's terrible. I sure hope that it's not intentionally done by Fantastical 2.

**Comment by vitorgalvao** [comment] 2017-02-11 14:28
You’re using the Mac App Store version of Fantastical. Mackup can’t deal with Mac App Store apps.

**Comment by zharmany** [comment] 2017-02-11 18:42
Argh! Is this due to sandboxing? Any idea why it shows different behavior on El Capitan versus Sierra?

One more reason to avoid the App Store...

**Comment by godbout** [comment] 2018-02-07 19:45
NNNNOOOOOOOO. No wonder why I can't get most of the apps that I've made a fork for (Magnet, HazeOver, Yoink) work. So sad 😓️

**Comment by paxperscientiam** [comment] 2018-11-15 21:52
@zanderzhng yep, sandboxing. Had the same problem with Office 2016 before realizing the cause. @lra, this could probably be closed because the problem is sandboxing and not Fantastical 2 per se.

**Comment by lra** [comment] 2019-01-14 07:01
@paxperscientiam thanks, I'm closing this. Feel free to reopen if needed.

**Closed by lra** 2019-01-14 07:01 UTC
