### ISSUE TITLE
feature request : add exclude directory option in config

### ISSUE THREAD

**Issue by anantshri** [lra/mackup#729] opened 2015-12-07 07:40 UTC
add support to mark few directories / files as excluded from mackup backup.

what we right now has is a whitelist. what i am requesting is a blacklist. depending on the situation both are apt solutions.

**Comment by lra** [comment] 2015-12-07 14:56
Dupe of https://github.com/lra/mackup/issues/602

**Closed by lra** 2015-12-07 14:56 UTC
