### ISSUE TITLE
No such file .mackup.cfg and KeyError: 'mackup'

### ISSUE THREAD

**Issue by amowu** [lra/mackup#445] opened 2015-01-26 11:53 UTC
I have backup on Dropbox one day ago, and config with `~/.mackup.cfg`
but today use `mackup restore` and get error on new mac.

error message:

```
$ mackup restore
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.1/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.1', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.1/libexec/lib/python2.7/site-packages/mackup/main.py", line 59, in main
    mackup_app.restore()
  File "/usr/local/Cellar/mackup/0.8.1/libexec/lib/python2.7/site-packages/mackup/application.py", line 122, in restore
    home_filepath))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 162, in samefile
    s1 = os.stat(f1)
OSError: [Errno 2] No such file or directory: '/Users/amowu/Dropbox/Mackup/.mackup.cfg'
```

why the `.mackup.cfg` change to Dropbox folder?

thanks.

**Comment by amowu** [comment] 2015-01-26 17:55
I'm copy my `~/.mackup.cfg` to `~/Dropbox/Mackup/`

and run `mackup restore`, get error:

```
$ mackup restore   
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.1/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.1', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.1/libexec/lib/python2.7/site-packages/mackup/main.py", line 69, in main
    app_names.remove(MACKUP_APP_NAME)
KeyError: 'mackup'
```

this is my `.mackup.cfg` :

```
[storage]
engine = dropbox
directory = Mackup

[applications_to_sync]
iterm2
oh-my-zsh
sublime-text-3
ssh
```

Thanks.

**Comment by glaszig** [comment] 2015-01-26 23:22
same here:

```
[storage]
engine = file_system
path = Mackup

[applications_to_sync]
sublime-text-3
git
bash-it
bash
```

**Comment by lra** [comment] 2015-01-26 23:34
Should be fixed in 0.8.2, sorry about that

**Closed** 2015-01-26 23:33 UTC

**Comment by amowu** [comment] 2015-01-27 05:32
Thanks so much :+1: when to release?

**Comment by lra** [comment] 2015-01-27 20:27
0.8.2 is out

**Comment by glaszig** [comment] 2015-01-27 23:07
https://github.com/lra/mackup/releases/tag/0.8.2 ?

**Comment by lra** [comment] 2015-01-27 23:39
Damn, forgot to push the tag =( I need to automate this, thx!
https://pypi.python.org/pypi/mackup

**Comment by lra** [comment] 2015-01-27 23:42
@glaszig  fixed

**Comment by glaszig** [comment] 2015-01-28 00:32
merci: Homebrew/homebrew#36298

**Comment by lra** [comment] 2015-01-28 03:54
Awsome =)

**Comment by wezzynl** [comment] 2015-02-25 20:28
Seems this error is back in 0.8.3 - Getting:

Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.3/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.3', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/main.py", line 56, in main
    mackup_app.restore()
  File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/application.py", line 125, in restore
    home_filepath))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 162, in samefile
    s1 = os.stat(f1)
OSError: [Errno 2] No such file or directory: '/Users/wezzy/Dotfiles/Mackup/.mackup.cfg'

My .mackup.cfg (which lives in my home dir):

[storage]
engine = file_system
path = Dotfiles

[applications_to_sync]
karabiner
keymo

**Comment by webpro** [comment] 2015-03-21 11:58
@lra, I also experience this issue (using v0.8.3), which essentially makes mackup useless for me (while it's such a great tool). Apparently it's trying to read `.mackup.cfg` from the configured `directory`. Would be great if you could look into this.

**Comment by lra** [comment] 2015-03-21 18:00
Sorry, but I have a hard time reproducing the problem here.
Can someone detail a broken config?
```
ls -l ~/.mackup.cfg
cat ~/.mackup.cfg
ls -l /path/to/Mackup/.mackup.cfg
cat /path/to/Mackup/.mackup.cfg
```
and tell me which command line action is generating the error?

Thanks.

**Comment by webpro** [comment] 2015-03-22 20:13
Just tried it, and the problem seems to be a symlinked file. When `~/.mackup.cfg` is not a symlink, things work just fine. (Still surprised it tries to read `[directory]/.mackup.cfg` if linked, though.)

**Comment by rsnts** [comment] 2015-08-24 19:11
Is this bug (not working with symlinks) referenced somewhere? Couldn't find it.
Thanks

**Comment by lra** [comment] 2015-08-26 16:14
@rsnts fixed by https://github.com/lra/mackup/commit/f765c009de633b5c8e787378cd62887b9771e81d
Will be in next release

**Comment by rsnts** [comment] 2015-08-26 16:18
Great!
Thank you!

**Comment by leoredi** [comment] 2015-10-30 16:05
Hi, I am having the same problem here, both when .ackup.cfg is a symlink to iCloud and when it is not. It complains telling me that 

```bash
Federicos-MacBook-Air:~ fredi$ ls -l .mackup.cfg 
lrwxr-xr-x  1 fredi  staff  76 30 Oct 17:02 .mackup.cfg -> /Users/fredi/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.mackup.cfg
Federicos-MacBook-Air:~ fredi$ cat .mackup.cfg 
[storage]
engine = icloud
Federicos-MacBook-Air:~ fredi$ ls -l /Users/fredi/Library/Mobile\ Documents/com~apple~CloudDocs/Mackup/.mackup.cfg
-rw-------  1 fredi  staff  26 28 Oct 11:10 /Users/fredi/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.mackup.cfg
Federicos-MacBook-Air:~ fredi$ cat /Users/fredi/Library/Mobile\ Documents/com~apple~CloudDocs/Mackup/.mackup.cfg
[storage]
engine = icloud


Federicos-MacBook-Air:~ fredi$ mackup restore
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 121, in main
    app.restore()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/application.py", line 157, in restore
    home_filepath))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 156, in samefile
    s2 = os.stat(f2)
OSError: [Errno 2] No such file or directory: '/Users/fredi/.ssh/config'
```
