### ISSUE TITLE
Exclude Vimperator/Pentadactyl history log?

### ISSUE THREAD

**Issue by chadluo** [lra/mackup#574] opened 2015-06-21 12:38 UTC
Both [Vimperator config](https://github.com/lra/mackup/blob/master/mackup/applications/vimperator.cfg) and [Pentadactyl config](https://github.com/lra/mackup/blob/master/mackup/applications/pentadactyl.cfg) required to backup their directories, which contains plugins but also history records (`./info/default/history-command` and `./info/default/history-search`). However daily normal use keeps changing these files and could create an annoying change log, which does not really need to be synced.

So can we choose to exclude those files while keep only the plugin directory?

**Comment by lra** [comment] 2015-06-22 15:49
not an option right now.
you have to explicitely list what to backup.

**Comment by darfink** [comment] 2015-06-26 20:48
Same issue with BetterTouchTool & `~/Library/Application Support/BetterTouchTool/Logs`.
Would be awesome if an option was available!

**Comment by lra** [comment] 2015-08-09 22:35
Dupe of https://github.com/lra/mackup/issues/602

**Closed by lra** 2015-08-09 22:35 UTC
