### ISSUE TITLE
'mackup backup' messages are somewhat deceptive

### ISSUE THREAD

**Issue by ChristopherA** [lra/mackup#345] opened 2014-10-05 22:43 UTC
As a new user of `mackup`, I had a bad experience because I installed it, used it to `mackup backup`, found that it backed up too much, so I created a .mackup.cfg file to just back the things I wanted backed up.

Then I went to my Dropbox folder and deleted the Mackup folder, believing that they were just backups. However, they are not — a number are the originals that are symbolically linked to the correct places, such that when I deleted the files from Dropbox, they were permanently deleted from my system (my Dropbox folder is NOT in my home dir, nor even on the same VOLUME, but on a DIFFERENT volume). It took me a while to recover from this!

I like the concept of mackup, and plan to use it as part of my own [dotfiles project](https://github.com/christophera/dotfiles), however, even as a sophisticated user the README and the output of the commands did not warn me sufficiently that this was not a simple backup copy.

Recommendations:

a) Add more information to the top level readme of what is really going on.

b) When you install `brew mackup` it should warn you to `mackup uninstall` before deleting any files that are backed up.

c) The messages when you `mackup backup` should be more explicit. They are not backing up the named paths and files, they are creating symbolic links, etc.

d) I'd seriously consider not calling this function backup at all -- from the wording you'd think I could restore from the last time I did `mackup backup`, but in fact any changes I made to the files since would be saved to Dropbox as well as these are symbolic links.

e) I'm a bit concerned about symbolic links across volumes failing if you backup things like bash, as the volume may not be loaded yet. You may want to warn people if on install you note that the Dropbox folder is not on the same volume as the home folder.

-- Christopher Allen

**Comment by aurbroszniowski** [comment] 2015-02-18 14:19
Same here, I executed mackup backup, it filled my dropbox so I rm'ed it then realized it had created no backup on my local drive, so I basically lost everything. No need to say that I am resentful against the people who advised it to me.
It is a frequent operation to test drive a utility, and erase it quickly when one realizes it is not an interesting tool, it would make sense to at least provide a backup on the hard drive and some big warning message, if this tool gets a large user base you're going to get more and more complaint.

**Comment by Timidger** [comment] 2015-02-19 19:28
I feel as though that adding another step in the process by changing `backup` to actually back up the files, and adding `link` to create links to the now backed up files would convolute the program too much.
`backup` in its current form works fine, it is just the name that causes confusion. If the command was changed to `link` or a similar name, I feel as though we would not have these problems. The name `backup` implies that it is simply making a copy, and for all the documentation it seems to look that way. So I don't think the implementation needs to change, just the command and it's documentation needs to change.

**Comment by lra** [comment] 2015-08-10 02:44
I agree, dupe of https://github.com/lra/mackup/issues/613

**Closed by lra** 2015-08-10 02:44 UTC
