### ISSUE TITLE
List of configuration_files as a set of filters/patterns

### ISSUE THREAD

**Issue by laughedelic** [lra/mackup#256] opened 2014-04-30 23:09 UTC
I wanted to add support for sbt (see #255) and was surprised, that only exact file paths work in mackup, because in the sbt case, for example, any file of the form `~/.sbt/0.13/*.sbt` (i.e. with any name) will be read by sbt for global settings. There are of course some naming conventions, but it's not flexible to rely on them. So patterns with wildcards would be very nice.

Better, would be great to have a list of ignored patterns. Like in `.gitignore`. Again, sbt is a great example:
- global settings in `~/.sbt/0.13/` are an sbt-project
- so when sbt reads it, it generates `target/` directory — which we don't want to backup
- everything in `~/.sbt/0.13/plugins/` is an sbt project too and again we want to take into accout all `*.sbt` files and ignore `target/` dir
- everything in `~/.sbt/0.13/project/project/` is again an sbt project... 
- everything in `~/.sbt/0.13/project/project/project/` is again an sbt project... and so on. It can be of any depth.

So if I could use gitignore-like patterns, I would write sbt.cfg simply like this
```props
[application]
name = SBT

[configuration_files]
.sbtconfig
.sbt/0.12/
.sbt/0.13/

[ignored_patterns]
target/
staging/
```

So I suggest two things:
- add ignored patterns — this will help not to synchronize different cache-files and etc.
- then if for a particular directory in the `configuration_files` list, set of the files that we want to ignore is not empty, link particular files, instead of linking the whole dir

**Comment by lra** [comment] 2015-08-10 03:01
Dupe of https://github.com/lra/mackup/issues/602

**Closed by lra** 2015-08-10 03:01 UTC
