### ISSUE TITLE
Feature request - add copy only option without move and symlink functionality

### ISSUE THREAD

**Issue by da-vaibhav** [lra/mackup#354] opened 2014-10-06 20:36 UTC
1. I think providing an option to just copy the config/ backup/ preference files without moving and later symlinking them would be a very helpful option for many because symbolic linking may disrupt the behaviour of applications and can also cause unknown behaviour where other applications try to match file paths. 
2. When user gets hold of copies of backup files in their Dropbox/ Drive folders then they can easily move/ arrange/ sort those files in Dropbox/ Drive folder, which won't break any app and will satisfy both purposes.

**Comment by tonyrobots** [comment] 2015-04-03 17:38
Yes, I was SHOCKED to see this behavior after what I thought would be a simple backup. Not cool at all. I don't think it should be the default; at the very least mackup should provide adequate warning about this.

**Comment by vitorgalvao** [comment] 2015-04-04 21:16
Duplicate of https://github.com/lra/mackup/issues/195.

As you can read there, this isn’t very likely to happen in mackup.

**Comment by joshuairl** [comment] 2015-07-27 11:59
My situation is that I have Dropbox on an external hard drive.  Mackup works great generally with symlinks until I disconnect and take my laptop away from my external drive.  Now NONE of my apps load correctly due to broken symlinks.

It would definitely be nice if there was at least an option to use copy to restore mackup settings instead of  symlinking?

I know this has been said before, just wanted to make sure I documented this.

**Comment by lra** [comment] 2015-08-10 02:36
Dupe of https://github.com/lra/mackup/issues/613

**Closed by lra** 2015-08-10 02:36 UTC

**Comment by jags613** [comment] 2018-11-03 03:11
This is fucking insane. Ruined what would've been a great little app.
