### ISSUE TITLE
Mackup Uninstall Issues

### ISSUE THREAD

**Issue by bernalpatrick** [lra/mackup#544] opened 2015-05-14 19:48 UTC
I am currently having trouble where I believe I have improperly uninstalled Mackup (deleted dropbox first instead of running the uninstall command). As a result, I am having this problem where things like Caffeine and Spectacle are going back to the original default configurations when I restart my computer. How do I make sure that I kill all the things that mackup has touched and restore all my preferred configurations?

**Comment by lra** [comment] 2015-05-14 19:56
Did you try `mackup uninstall`?

**Comment by bernalpatrick** [comment] 2015-05-14 20:02
yes.  i get this:
Error: Unable to find the Mackup folder: /Users/pbernal/Dropbox/Mackup
You might want to backup some files or get your storage directory synced first.

Mind you, I deleted the dropbox folder first instead of running the uninstall command.

Things I have tried:
Reinstalling/Backing up Mackup and then uninstall
Deleting some config files that I can see were affected by mackup

**Comment by lra** [comment] 2015-05-15 01:16
I guess your only option would be to put back dropbox, sorry.

TODO: Make mackup remove dangling links

**Comment by lra** [comment] 2015-08-09 23:16
Dupe of https://github.com/lra/mackup/issues/612

**Closed by lra** 2015-08-09 23:16 UTC
Labels: TODO
