### ISSUE TITLE
iTerm2 DynamicProfiles FileExistsError

### ISSUE THREAD

**Issue by johanmolen** [lra/mackup#1855] opened 2022-09-01 10:01 UTC
Im getting the following error when trying to backup iTerm2 DynamicProfiles:

```
Backing up Library/Application Support/iTerm2/DynamicProfiles ...
A folder named /Users/username/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles already exists in the backup.
Are you sure that you want to replace it? <Yes|No> Yes
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.35', 'console_scripts', 'mackup')())
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/application.py", line 114, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles' -> '/Users/username/Library/Application Support/iTerm2/DynamicProfiles'
```

Is this a bug or something on my side?

**Comment by fharper** [comment] 2022-09-02 00:25
I have the same issue

**Comment by steveshi** [comment] 2022-09-06 10:24
I have the same issue

**Comment by joshmedeski** [comment] 2022-09-06 17:00
It looks like it's related to `DynamicProfiles` being a directory. Please try this and let us know if it's still failing.

1. Move `DynamicProfiles` from your mackup directory to somewhere else as a temporary backup.
2. Rerun mackup backup (you should no longer see "...already exists in the backup")

Let me know if this works for any of you and we can further investigate the root cause.

**Comment by johanmolen** [comment] 2022-09-06 20:21
@joshmedeski removing the folder with iTerm2 results in the same. 

Removing the folder with the terminal app and then run `mackup backup` works, but once I start iTerm2 again the folder is recreated and I get the same error again.

**Comment by johanmolen** [comment] 2022-09-06 20:22
The recreation is normal as listed here:
https://iterm2.com/documentation-dynamic-profiles.html

**Comment by joshmedeski** [comment] 2022-09-06 20:26
Hmm, we've run into a similar issue with other apps where the application (i.e. iTerm) overwrites files and mackup loses its symbolic link. I wonder if it's the same kind of issue here.

**Comment by johanmolen** [comment] 2022-09-06 20:28
Is there something I can run to get more debug information?

**Comment by joshmedeski** [comment] 2022-09-06 20:36
There is a `--verbose` flag. Feel free to rerun the command with that flag and let us know if there's any further information given.

**Comment by johanmolen** [comment] 2022-09-06 20:45
Nope no additional info 👎

**Comment by xingfanxia** [comment] 2022-09-21 09:11
Getting the same issue, any fix/work around yet? Moving the Dynamic profile in mackup backup doesn't work

**Comment by xingfanxia** [comment] 2022-09-21 09:12
```╭─   ~ ··················································································································································································  system  02:09:14
╰─❯ mv "/Users/xingfanxia/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles" ~/Downloads
╭─   ~ ··················································································································································································  system  02:09:24
╰─❯ mackup backup
Backing up Library/Application Support/iTerm2/DynamicProfiles ...
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.35', 'console_scripts', 'mackup')())
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/application.py", line 121, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/xingfanxia/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles' -> '/Users/xingfanxia/Library/Application Support/iTerm2/DynamicProfiles'
╭─   ~ ··················································································································································································  system  02:09:26
╰─❯ mv '/Users/xingfanxia/Library/Application Support/iTerm2/DynamicProfiles' ~/Downloads
╭─   ~ ··················································································································································································  system  02:11:52
╰─❯ mackup backup
Backing up Library/Preferences/com.googlecode.iterm2.plist ...
Backing up Library/Application Support/iTerm2/DynamicProfiles ...
A folder named /Users/xingfanxia/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles already exists in the backup.
Are you sure that you want to replace it? <Yes|No> Yes
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.35', 'console_scripts', 'mackup')())
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/application.py", line 114, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/xingfanxia/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles' -> '/Users/xingfanxia/Library/Application Support/iTerm2/DynamicProfiles'```

**Comment by cyberfunkr** [comment] 2022-09-30 04:05
Getting the same problem

**Comment by ralts00** [comment] 2022-10-06 18:00
Same issue here

**Comment by gxcodes** [comment] 2022-10-14 02:04
Still the same issue in mackup version 0.8.36

**Comment by getvega** [comment] 2022-10-14 08:44
@LucasLarson [PR](https://github.com/LucasLarson/mackup/commit/bfe775f5f87ede40033f2f3881cd6b89738466c2) fixes this form me 👍 , thanks

**Comment by fharper** [comment] 2022-10-26 17:52
I updated `iterm2.cfg` based on #1864, I deleted my iTerm2 backup from my Mackup folder, but when I run `mackup backup` I get the same error. Anything I'm missing?

**Comment by PierBJX** [comment] 2022-11-17 11:29
> Updating my `iterm2.cfg` based on #1864, I was able to run `mackup backup`. Would be great to get this released!
@m-roberts @getvega 
Where did you modify this file? Where is it located?

**Comment by PierBJX** [comment] 2022-11-17 13:43
Thanks

**Comment by itoumlilt** [comment] 2022-11-19 12:13
A simpler workaround, closing iTerm.app prevent it from recreating `DynamicProfiles`.
For example, try to backup from `Terminal.app` or another term:
```bash
killall iTerm2
mackup backup
```

**Comment by vordenken** [comment] 2023-01-25 10:18
The issue still exists... Any information about when this get updated in the release?

**Comment by ilium007** [comment] 2023-02-04 11:35
Still experiencing this same issue

**Closed** 2023-03-24 17:07 UTC

**Comment by elmpp** [comment] 2023-04-01 08:06
I'm still getting the iterm2 specific error with latest release of `0.8.37`:

```
Backing up
  /Users/matt/Library/Preferences/com.googlecode.iterm2.plist
  to
  /Users/matt/Library/CloudStorage/GoogleDrive-EMAIL_ADDRESS/My Drive/syncable_apps_mackup/Library/Preferences/com.googlecode.iterm2.plist ...
A file named /Users/matt/Library/CloudStorage/GoogleDrive-EMAIL_ADDRESS/My Drive/syncable_apps_mackup/Library/Preferences/com.googlecode.iterm2.plist already exists in the backup.
Are you sure that you want to replace it? <Yes|No> yes
Backing up
  /Users/matt/.config/iterm2/AppSupport/DynamicProfiles
  to
  /Users/matt/Library/CloudStorage/GoogleDrive-EMAIL_ADDRESS/My Drive/syncable_apps_mackup/.config/iterm2/AppSupport/DynamicProfiles ...
A folder named /Users/matt/Library/CloudStorage/GoogleDrive-EMAIL_ADDRESS/My Drive/syncable_apps_mackup/.config/iterm2/AppSupport/DynamicProfiles already exists in the backup.
Are you sure that you want to replace it? <Yes|No> yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.37', 'console_scripts', 'mackup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/application.py", line 112, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/matt/Library/CloudStorage/GoogleDrive-EMAIL_ADDRESS/My Drive/syncable_apps_mackup/.config/iterm2/AppSupport/DynamicProfiles' -> '/Users/matt/.config/iterm2/AppSupport/DynamicProfiles'
```

**Comment by liaozihang** [comment] 2023-04-15 16:42
> I'm still getting the iterm2 specific error with latest release of `0.8.37`:

same issue here .
Perhaps related to the default settings of Iterm2:

![default settings](https://user-images.githubusercontent.com/31334545/232238591-8e0f0ece-9f49-41f7-ae38-7a52a4f3752b.png)

**Comment by Jendker** [comment] 2023-05-11 22:00
The issue still persists on the latest release from homebrew. Run into some troubles with iTerm because of it.

**Comment by scottmc42** [comment] 2023-06-21 00:33
I'm getting the same problem on a different computer; confirmed the [1864](https://github.com/lra/mackup/pull/1864/files) update in my version.

```text
Backing up .config/iterm2/AppSupport/DynamicProfiles ...
A folder named /Users/me/backup/Mackup/.config/iterm2/AppSupport/DynamicProfiles already exists in the backup.
Are you sure that you want to replace it? <Yes|No> y
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.37', 'console_scripts', 'mackup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/application.py", line 112, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/me/backup/Mackup/.config/iterm2/AppSupport/DynamicProfiles' -> '/Users/me/.config/iterm2/AppSupport/DynamicProfiles'
```
